Repository hctnm2/Open-Source-Enthusiast, pull requests merged in 2021-10, with the labels that each got.

#29 added my name
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#30 added rohan nair to index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#31 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#32 chore: added my github-profile
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#33 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#34 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#36 Added my name
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#37 Rahul laha github profile added
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#38 added my name
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#39 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#40 added my name
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#41 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#48 Updated index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#49 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#55 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#56 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#57 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#58 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#59 Updated index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#60 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#61 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#62 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#63 Please Confirm My Pull Request
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#64 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#65 Made changes to index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#66 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#67 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#68 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#69 Create complex-numbers-addition.cpp
  codes/complex-numbers-addition.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#71 Added a name
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#72 Updated index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#74 Create ArticulationPoint.java
  codes/ArticulationPoint.java
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#75 Added Vishal Kumar Sharma
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#76 Added name in index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#77 Added myself...
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#78 adding name dice code
  Codes/dice.py
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#79 love tyagi git profile setup.
  codes/ArticulationPoint.java
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#80 Added Factorial.go
  Codes/factorial.go
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#81 Name added
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#82 Added my Github Profile
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#83 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#84 Added name
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#86 Added name
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#87 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#88 Added line of text
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#89 Added my GitHub profile link in index.html file
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#92 Added new contributor
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#93 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#94 Added Contributor
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#95 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#96 Updated index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#97 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#98 Basic HTML Code illustrations for beginners
  Codes/Basics/Change.html
  Codes/Basics/DSC_0231.JPG
  Codes/Basics/Index.html
  Codes/Basics/README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#100 Added my name and profile
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#105 Added my github profile link
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#106 added dijkstra
  Codes/dijkstra.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#107 Create fibonacciusingmemoization.cpp
  codes/fibonacciusingmemoization.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#108 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#109 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#110 add link
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#111 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#112 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#113 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#114 a
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#115 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#116 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#117 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#118 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#119 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#120 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#121 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#122 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#123 added floyd all pair shortest path
  Codes/floyd.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#124 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#125 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#126 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#127 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#128 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#130 Added github id
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#131 add me
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#133 uploaded a simple html based currency converter
  Codes/currencyConverter.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#134 Added my Github profile
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#135 Updated index.html file with github id
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#136 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#137 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#138 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#139 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#140 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#141 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#142 Added line of text
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#143 update : index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#144 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#145 Added myself in index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#146 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#147 Added javascript reverseArray and added to index.html
  JavaScript/reverseArray.js
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#148 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#149 Added my github profile
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#150 Updated Index.html in the proposed format
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#151 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#153 Added name to index
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#154 Create half-pyramid.c
  codes/half-pyramid.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#156 Edited index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#161 Update index.html - add name
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#162 Create full-pyramid.c
  codes/full-pyramid.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#163 Updated a new line in list
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#167 Edited index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#168 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#169 added link for sahilsujeet1 profile
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#170 sine series
  Codes/sineseries.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#171 I am added a smooth transition to the instruction button. Now the button will smoothly change to the next color while hovering on it,
  .vscode/settings.json
  style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#172 Added css and my name.
  JavaScript/reverseArray.js
  index.html
  style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#173 update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#174 UPDATE
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#175 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#176 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#177 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#178 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#179 my name is added.
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#181 Add files via upload
  Codes/bankers.java
  Codes/dsa.c
  Codes/paging.java
  Codes/tracks.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#182 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#186 something add my name to contribution
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#187 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#188 changes in index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#189 Create insertionSort.c
  Codes/insertionSort.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#190 Added pasindujr line in index.html and snake_game.html into Codes dir…
  Codes/snake_game.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#191 updated new line as instructed
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#192 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#193 add sofyanmoch
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#194 add Bipartite graph check C++
  Codes/Bipartite_Graph.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#195 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#196 add Structurally identical binary trees C++
  Codes/StructurallyIdentical.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#197 New line added in index.html file
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#198 Merge pull request
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#199 Create Symmetricpairsofarray.cpp
  codes/Symmetricpairsofarray.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#200 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#300 Create Median_of_2Array.py
  Codes/Median_of_2Array.py
Labels: hacktoberfest-accepted

#301 Create Palindrome.cpp
  Codes/Palindrome.cpp
Labels: hacktoberfest-accepted

#451 Create Compute-Polynomial.cpp
  Codes/Compute-Polynomial.cpp
Labels: hacktoberfest-accepted

#452 Update index.html
  index.html
Labels: hacktoberfest-accepted

#454 Create Rat_In_a_maze.cpp
  Codes/Rat_In_a_maze.cpp
Labels: hacktoberfest-accepted

#457 Create snake.py
  Codes/snake.py
Labels: hacktoberfest-accepted
